# Numpy

# Numerical Python designed for numerical operation

- N - dimensionl Array
- Math Operation
- Broadcasting
- Integrate with other liberary (pandas, Matploib, TensorFLow)
- Effciency (Written in C language)
- Memory Efficiency

# pip install numpy

In [2]:
import numpy as np #(Shift + Enter)

In [6]:
arr = np.array([1,2,3,4])

In [9]:
print(arr)
print(type(arr))

[1 2 3 4]
<class 'numpy.ndarray'>


In [10]:
l = [1, 2, 3, 4]
print(l)
print(type(l))

[1, 2, 3, 4]
<class 'list'>


# Numpy Vs Python List

# Speed

In [11]:
import time

In [12]:
#NumPy Array
arr = np.arange(1000000) #[0 1 2 3 .... 1000000]
start = time.time()
arr = arr * 2
print("NumPy Time: ", time.time() -  start)

NumPy Time:  0.002199888229370117


In [14]:
#Python List
lst = list(range(1000000)) #[0 1 2 3 .... 1000000]
start = time.time()
lst = [x * 2 for x in lst]
print("Python List Time: ", time.time() -  start)

Python List Time:  0.03722500801086426


# Memory Efficiency

In [16]:
import sys

In [17]:
# NumPy Array
arr = np.array([1, 2, 3, 4])
print("Numpy Array Memory:", arr.nbytes, "bytes")

Numpy Array Memory: 32 bytes


In [18]:
# Python List
lst = [1, 2, 3, 4]
print("Python List Memory: ", sys.getsizeof(lst) + sum(sys.getsizeof(x) for x in lst), "bytes")

Python List Memory:  200 bytes


# Type Consistency

In [19]:
lst = [1, 2, 3, 4, "Mohit"]

In [20]:
lst

[1, 2, 3, 4, 'Mohit']

In [23]:
arr = np.array([1, 2, 3, 4, "Mohit"])

In [24]:
arr

array(['1', '2', '3', '4', 'Mohit'], dtype='<U21')

# Math Operation

In [36]:
#Numpy Array ()
arr = np.array([1, 2, 3, 4])
print("NumPy Sum:", np.sum(arr))
print("NumPy Mean:", np.mean(arr))

NumPy Sum: 10
NumPy Mean: 2.5


In [37]:
%timeit np.sum(arr)

939 ns ± 14.5 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)


In [33]:
lst = [1, 2, 3, 4]
print("Python Sum:", sum(lst))
print("Python Mean:", sum(lst)/len(lst))

Python Sum: 10
Python Mean: 2.5


In [38]:
%timeit sum(lst)

30.6 ns ± 1.43 ns per loop (mean ± std. dev. of 7 runs, 10,000,000 loops each)


# ARRAY

In [40]:
x = [1, 2, 3 ,4]
y = np.array(x)
print(y)
print(type(y))
y = np.array([1, 2, 3, 4, 5])
print(y)
print(type(y))

[1 2 3 4]
<class 'numpy.ndarray'>
[1 2 3 4 5]
<class 'numpy.ndarray'>


In [41]:
l = []
for i in range(1,5):
    val = int(input("enter:"))
    l.append(val)

print(np.array(l))

enter: 10
enter: 11
enter: 12
enter: 13


[10 11 12 13]


# Dimension in Array
- 1-D Array
- 2-D Array
- 3-D Array
- Higher Dimensional Array

In [43]:
x = [1, 2 ,3 ,4]
y = np.array(x)
print(y.ndim)

1


In [45]:
ar2 = np.array([[1, 2, 3], [4, 5, 6]])
print(ar2)
print(ar2.ndim)

[[1 2 3]
 [4 5 6]]
2


In [47]:
ar3 = np.array([[[1, 2, 3], [1, 2, 3], [1, 2, 3]]])
print(ar3)
print(ar3.ndim)

[[[1 2 3]
  [1 2 3]
  [1 2 3]]]
3


In [49]:
arn = np.array([1, 2, 3, 4], ndmin = 10)
print(arn)
print(arn.ndim)

[[[[[[[[[[1 2 3 4]]]]]]]]]]
10


# Special NumPy Array

- Array Fill with 0's
- Array Fill with 1's
- Create an empty array (junk)
- Range array
- Array diagonal element filled with 1's
- Create an array with values that are spaced lineraly in specified interval

In [57]:
zeros_array = np.zeros((5, 10)) # 5 - Row, 10 - Col
print(zeros_array)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


In [56]:
ones_array = np.ones((4, 5))
print(ones_array)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [67]:
empty = np.empty((4, 4))
print(empty)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [4]:
range_array = np.arange(0, 10, 1) # Start = 0 Stop = 10 Step = 2
print(range_array)

[0 1 2 3 4 5 6 7 8 9]


In [8]:
diagonal_array = np.eye(5, 5) # 3 X 3
print(diagonal_array)


[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [20]:
linear_array = np.linspace(0, 20, 5) # Start = 0, Stop = 1, Number of point = 5
print(linear_array)

[ 0.  5. 10. 15. 20.]


# NumPy Random Number Function

# rand()

In [24]:
# [0, 1)
# 1-D
rand_array = np.random.rand(5)
print(rand_array)
print("-------")
rand_array = np.random.rand(2, 5)
print(rand_array)

[0.45635767 0.98722992 0.75784921 0.41853613 0.2434861 ]
-------
[[0.08666031 0.28814108 0.12252612 0.99611969 0.07413143]
 [0.46269285 0.24553255 0.80401323 0.06790138 0.54717557]]


# randn()

In [29]:
# generate random values close to 0 and it can include negative value as well
randn_array = np.random.randn(5)
print(randn_array)

[ 0.49067444  0.88204834  0.35152695 -1.0163074  -0.80175977]


# randint()

In [35]:
rand_int = np.random.randint(10, 50, 10)
print(rand_int)
print()
rand_int = np.random.randint(10, 50, size=(3,3))
print(rand_int)

[18 21 43 30 22 12 20 11 45 27]

[[46 11 31]
 [25 42 45]
 [24 40 18]]


# Data Type of NumPy Array

In [40]:
# Integer Data Type int32, int64
int_array = np.array([1,2,3,4], dtype=np.int32) # Java Int
print(int_array.dtype)
print(int_array)

int32
[1 2 3 4]


In [41]:
# Converting int to float
float_array = int_array.astype(float)
print(float_array)

[1. 2. 3. 4.]


In [45]:
# float32
float_array = np.array([1.34,2.56,3.66,4.77], dtype=np.float32)
print(float_array.dtype)
print(float_array)

float32
[1.34 2.56 3.66 4.77]


In [44]:
# Convert float to int
int_array = float_array.astype(int)
print(int_array)

[1 2 3 4]


In [47]:
# Boolean Data type
bool_array = np.array([True, False, True], dtype='?')
print(bool_array.dtype)

bool


In [48]:
# Convert Bool array to int
int_array = bool_array.astype(int)
print(int_array)

[1 0 1]


In [52]:
# String
# np.string_ why it not worked
string_array = np.array(["hello", "world"], dtype='S')
print(string_array.dtype)

|S5


In [55]:
#Complex Data type
complex_array = np.array([1 + 2j, 3 + 4j], dtype=np.complex64)
print(complex_array.dtype)

complex64


In [58]:
# Date
date_array = np.array(['2024-01-01', '2024-02-01'], dtype=np.datetime64)
print(date_array.dtype)

datetime64[D]


# NumPy Arithmetic Operation

In [59]:
# you want increasing the price of all items in a store by 5$
price = np.array([10, 20, 30, 40, 50])
price = price + 5
print(price)

[15 25 35 45 55]


In [62]:
# You want to combine the sales from two region
region_a_sales = np.array([100, 200, 300])
region_b_sales = np.array([150, 250, 350])

total_sales = region_a_sales + region_b_sales
print(total_sales)

[250 450 650]


In [63]:
# you want decrese the price of all items in a store by 5$
price = np.array([10, 20, 30, 40, 50])
price = price - 5
print(price)

[ 5 15 25 35 45]


In [64]:
# You want to combine the sales from two region
region_a_sales = np.array([100, 200, 300])
region_b_sales = np.array([150, 250, 350])

total_sales = region_b_sales - region_a_sales
print(total_sales)

[50 50 50]


In [65]:
# Calculate the revenue for each product by multiply price and quantitly sold
prices = np.array([5, 10, 15])
quantities = np.array([2, 5, 1])
revenue = prices * quantities
print(revenue)

[10 50 15]


In [68]:
# Calculate the average price per item
total_prices = np.array([10, 50, 15])
quantities = np.array([2, 5, 1])
average_price = total_prices / quantities
print(average_price)

[ 5. 10. 15.]


In [70]:
# You want to apply a multipler to all grade
grade = np.array([70, 80, 90, 100])

multiplier = 1.1
cureved_grade = grade * multiplier
print(cureved_grade)

[ 77.  88.  99. 110.]
