# Numpy

# Numerical Python designed for numerical operation

- N - dimensionl Array
- Math Operation
- Broadcasting
- Integrate with other liberary (pandas, Matploib, TensorFLow)
- Effciency (Written in C language)
- Memory Efficiency

# pip install numpy

In [2]:
import numpy as np #(Shift + Enter)

In [6]:
arr = np.array([1,2,3,4])

In [9]:
print(arr)
print(type(arr))

[1 2 3 4]
<class 'numpy.ndarray'>


In [10]:
l = [1, 2, 3, 4]
print(l)
print(type(l))

[1, 2, 3, 4]
<class 'list'>


# Numpy Vs Python List

# Speed

In [11]:
import time

In [12]:
#NumPy Array
arr = np.arange(1000000) #[0 1 2 3 .... 1000000]
start = time.time()
arr = arr * 2
print("NumPy Time: ", time.time() -  start)

NumPy Time:  0.002199888229370117


In [14]:
#Python List
lst = list(range(1000000)) #[0 1 2 3 .... 1000000]
start = time.time()
lst = [x * 2 for x in lst]
print("Python List Time: ", time.time() -  start)

Python List Time:  0.03722500801086426


# Memory Efficiency

In [16]:
import sys

In [17]:
# NumPy Array
arr = np.array([1, 2, 3, 4])
print("Numpy Array Memory:", arr.nbytes, "bytes")

Numpy Array Memory: 32 bytes


In [18]:
# Python List
lst = [1, 2, 3, 4]
print("Python List Memory: ", sys.getsizeof(lst) + sum(sys.getsizeof(x) for x in lst), "bytes")

Python List Memory:  200 bytes


# Type Consistency

In [19]:
lst = [1, 2, 3, 4, "Mohit"]

In [20]:
lst

[1, 2, 3, 4, 'Mohit']

In [23]:
arr = np.array([1, 2, 3, 4, "Mohit"])

In [24]:
arr

array(['1', '2', '3', '4', 'Mohit'], dtype='<U21')

# Math Operation

In [36]:
#Numpy Array ()
arr = np.array([1, 2, 3, 4])
print("NumPy Sum:", np.sum(arr))
print("NumPy Mean:", np.mean(arr))

NumPy Sum: 10
NumPy Mean: 2.5


In [37]:
%timeit np.sum(arr)

939 ns ± 14.5 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)


In [33]:
lst = [1, 2, 3, 4]
print("Python Sum:", sum(lst))
print("Python Mean:", sum(lst)/len(lst))

Python Sum: 10
Python Mean: 2.5


In [38]:
%timeit sum(lst)

30.6 ns ± 1.43 ns per loop (mean ± std. dev. of 7 runs, 10,000,000 loops each)


# ARRAY

In [40]:
x = [1, 2, 3 ,4]
y = np.array(x)
print(y)
print(type(y))
y = np.array([1, 2, 3, 4, 5])
print(y)
print(type(y))

[1 2 3 4]
<class 'numpy.ndarray'>
[1 2 3 4 5]
<class 'numpy.ndarray'>


In [41]:
l = []
for i in range(1,5):
    val = int(input("enter:"))
    l.append(val)

print(np.array(l))

enter: 10
enter: 11
enter: 12
enter: 13


[10 11 12 13]


# Dimension in Array
- 1-D Array
- 2-D Array
- 3-D Array
- Higher Dimensional Array

In [43]:
x = [1, 2 ,3 ,4]
y = np.array(x)
print(y.ndim)

1


In [45]:
# [1, 2, 3]
# [4, 5, 6]
ar2 = np.array([[1, 2, 3], [4, 5, 6]])
print(ar2)
print(ar2.ndim)

[[1 2 3]
 [4 5 6]]
2


In [47]:
ar3 = np.array([[[1, 2, 3], [1, 2, 3], [1, 2, 3]]])
print(ar3)
print(ar3.ndim)

[[[1 2 3]
  [1 2 3]
  [1 2 3]]]
3


In [49]:
arn = np.array([1, 2, 3, 4], ndmin = 10)
print(arn)
print(arn.ndim)

[[[[[[[[[[1 2 3 4]]]]]]]]]]
10


# Special NumPy Array

- Array Fill with 0's
- Array Fill with 1's
- Create an empty array (junk)
- Range array
- Array diagonal element filled with 1's
- Create an array with values that are spaced lineraly in specified interval

In [57]:
zeros_array = np.zeros((5, 10)) # 5 - Row, 10 - Col
print(zeros_array)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


In [56]:
ones_array = np.ones((4, 5))
print(ones_array)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [67]:
empty = np.empty((4, 4))
print(empty)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [4]:
range_array = np.arange(0, 10, 1) # Start = 0 Stop = 10 Step = 2
print(range_array)

[0 1 2 3 4 5 6 7 8 9]


In [8]:
diagonal_array = np.eye(5, 5) # 3 X 3
print(diagonal_array)


[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [3]:
linear_array = np.linspace(0, 20, 6) # Start = 0, Stop = 1, Number of point = 5
print(linear_array)

[ 0.  4.  8. 12. 16. 20.]


# NumPy Random Number Function

# rand()

In [24]:
# [0, 1)
# 1-D
rand_array = np.random.rand(5)
print(rand_array)
print("-------")
rand_array = np.random.rand(2, 5)
print(rand_array)

[0.45635767 0.98722992 0.75784921 0.41853613 0.2434861 ]
-------
[[0.08666031 0.28814108 0.12252612 0.99611969 0.07413143]
 [0.46269285 0.24553255 0.80401323 0.06790138 0.54717557]]


# randn()

In [29]:
# generate random values close to 0 and it can include negative value as well
randn_array = np.random.randn(5)
print(randn_array)

[ 0.49067444  0.88204834  0.35152695 -1.0163074  -0.80175977]


# randint()

In [35]:
rand_int = np.random.randint(10, 50, 10)
print(rand_int)
print()
rand_int = np.random.randint(10, 50, size=(3,3))
print(rand_int)

[18 21 43 30 22 12 20 11 45 27]

[[46 11 31]
 [25 42 45]
 [24 40 18]]


# Data Type of NumPy Array

In [40]:
# Integer Data Type int32, int64
int_array = np.array([1,2,3,4], dtype=np.int32) # Java Int
print(int_array.dtype)
print(int_array)

int32
[1 2 3 4]


In [41]:
# Converting int to float
float_array = int_array.astype(float)
print(float_array)

[1. 2. 3. 4.]


In [45]:
# float32
float_array = np.array([1.34,2.56,3.66,4.77], dtype=np.float32)
print(float_array.dtype)
print(float_array)

float32
[1.34 2.56 3.66 4.77]


In [44]:
# Convert float to int
int_array = float_array.astype(int)
print(int_array)

[1 2 3 4]


In [47]:
# Boolean Data type
bool_array = np.array([True, False, True], dtype='?')
print(bool_array.dtype)

bool


In [48]:
# Convert Bool array to int
int_array = bool_array.astype(int)
print(int_array)

[1 0 1]


In [52]:
# String
# np.string_ why it not worked
string_array = np.array(["hello", "world"], dtype='S')
print(string_array.dtype)

|S5


In [55]:
#Complex Data type
complex_array = np.array([1 + 2j, 3 + 4j], dtype=np.complex64)
print(complex_array.dtype)

complex64


In [58]:
# Date
date_array = np.array(['2024-01-01', '2024-02-01'], dtype=np.datetime64)
print(date_array.dtype)

datetime64[D]


# NumPy Arithmetic Operation

In [59]:
# you want increasing the price of all items in a store by 5$
price = np.array([10, 20, 30, 40, 50])
price = price + 5
print(price)

[15 25 35 45 55]


In [62]:
# You want to combine the sales from two region
region_a_sales = np.array([100, 200, 300])
region_b_sales = np.array([150, 250, 350])

total_sales = region_a_sales + region_b_sales
print(total_sales)

[250 450 650]


In [63]:
# you want decrese the price of all items in a store by 5$
price = np.array([10, 20, 30, 40, 50])
price = price - 5
print(price)

[ 5 15 25 35 45]


In [64]:
# You want to combine the sales from two region
region_a_sales = np.array([100, 200, 300])
region_b_sales = np.array([150, 250, 350])

total_sales = region_b_sales - region_a_sales
print(total_sales)

[50 50 50]


In [65]:
# Calculate the revenue for each product by multiply price and quantitly sold
prices = np.array([5, 10, 15])
quantities = np.array([2, 5, 1])
revenue = prices * quantities
print(revenue)

[10 50 15]


In [68]:
# Calculate the average price per item
total_prices = np.array([10, 50, 15])
quantities = np.array([2, 5, 1])
average_price = total_prices / quantities
print(average_price)

[ 5. 10. 15.]


In [70]:
# You want to apply a multipler to all grade
grade = np.array([70, 80, 90, 100])

multiplier = 1.1
cureved_grade = grade * multiplier
print(cureved_grade)

[ 77.  88.  99. 110.]


# Numpy Arithmetic Function

In [4]:
# Sum, Prod, cumsum, min, msx, mean, medium... etc

In [6]:
# Sum of elements
arr = np.array([1,2,3,4,5])
result = np.sum(arr)
print(result)

15


In [7]:
# Product of elements
prod = np.prod(arr)
print(prod)

120


In [9]:
# Cumulative Sum
# [1,2,3,4,5] --> [1, 3, 6, 10, 15]
cum_result = np.cumsum(arr)
print(cum_result)

[ 1  3  6 10 15]


In [10]:
# Cumulative product
cum_prod_result = np.cumprod(arr)
print(cum_prod_result)

[  1   2   6  24 120]


In [11]:
# Min
min_val = np.min(arr)
print(min_val)

1


In [12]:
# Max
max_val = np.max(arr)
print(max_val)

5


In [14]:
# Range (ptp)
result = np.ptp(arr)
print("Max - Min:", result)

Max - Min: 4


In [15]:
# Min Index
min_val_index = np.argmin(arr)
print(min_val_index)

0


In [16]:
# Max Index
max_val_index = np.argmax(arr)
print(max_val_index)

4


In [17]:
# Pertentile
# Find the 50th percentile (median)
result = np.percentile(arr, 50)
print(result)

3.0


In [19]:
# Median
result_median = np.median(arr)
print(result_median)

3.0


# Shape & Reshaping in Numpy Array

- 1D shape (n, ) n = number of element
- 2D shape (row, col)
- 3D shape (depth, rows, column)

In [23]:
arr_1d = np.array([1,2,3,4,5,6])
print(arr_1d.ndim)
print(arr_1d.shape)

1
(6,)


In [25]:
# [1,2]
# [2,3]
# [4,5]
arr_2d = np.array([[1,2], [2,3], [4, 5]])
print(arr_2d.shape)

(3, 2)


In [27]:
arr_3d = np.array([[[1, 2],[3,4]],[[4, 4],[5,5]]])
print(arr_3d.shape)

(2, 2, 2)


In [52]:
arr_1d = np.array([1,2,3,4,5,6, 7, 8, 9])

""" 
(3 X 2)
1, 2
3, 4
5 ,6
7 ,8
9, ?
"""
reshap = arr_1d.reshape(3, 3)
print(reshap)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [54]:
auto_reshape = arr_1d.reshape(-1, 3)
print(auto_reshape)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [62]:
# Flat an array
"""
[[1 2 3]
 [4 5 6]]
"""
arr_2d = np.array([[1,2,3], [4,5,6]])
print(arr_2d)
print()
flat_result = arr_2d.flatten()
print(flat_result)

squz = np.squeeze(arr_2d)
print(squz)

[[1 2 3]
 [4 5 6]]

[1 2 3 4 5 6]
[[1 2 3]
 [4 5 6]]


In [49]:
# Resize of array
arr_1d = np.array([1,2,3,4,5])
resize = np.resize(arr_1d, (10, 10))
print(resize)

[[1 2 3 4 5 1 2 3 4 5]
 [1 2 3 4 5 1 2 3 4 5]
 [1 2 3 4 5 1 2 3 4 5]
 [1 2 3 4 5 1 2 3 4 5]
 [1 2 3 4 5 1 2 3 4 5]
 [1 2 3 4 5 1 2 3 4 5]
 [1 2 3 4 5 1 2 3 4 5]
 [1 2 3 4 5 1 2 3 4 5]
 [1 2 3 4 5 1 2 3 4 5]
 [1 2 3 4 5 1 2 3 4 5]]


In [56]:
# Transponse an array
arr_2d = np.array([[1, 2, 3], [4, 5, 6]])
print(arr_2d)
print("-----------")
transponse = arr_2d.T
print(transponse)

[[1 2 3]
 [4 5 6]]
-----------
[[1 4]
 [2 5]
 [3 6]]


In [59]:
# Adding a New Axis
" 1, 2, 3 "
"""
(3 X 1)
1
2
3
"""
arr_1d = np.array([1,2,3])
print(arr_1d)
expanded = arr_1d[:,np.newaxis]
print(expanded)

[1 2 3]
[[1]
 [2]
 [3]]


# Broadcasting in NumPy?

# When Boroacasting works
 - Arrays have the same shape
 - Array have compitable shape (either both row/col are same or one of them is 1)

```
3 X 3 +  3 X 1   ===> 3 X 3
-----    -----       --------
1,2,3    1           2, 4 ,6
4,5,6    2           5, 7, 8
7,8,9    3           8, 10, 11

```

```
  Array 1     Array 2    Result
 (3, 3)        (3, 3)     (3, 3)
 (3, 3)        (3, 1)     (3, 3)
 (3, 1)        (1, 3)     (3, 3)
 (3,)          (3, 3)     (3, 3)
 ```

In [1]:
import numpy as np

In [11]:
arr1 = np.array([[1,2,3],[4,5,6]]) # (2, 3) 2 X 3
arr2 = np.array([1, 2, 3]) # (1,)
print(arr2)
print(arr2)
print()
print(arr1)
print()
result = arr1 - arr2
print(result)

[1 2 3]
[1 2 3]

[[1 2 3]
 [4 5 6]]

[[0 0 0]
 [3 3 3]]


# Index and Slicing in Array

In [15]:
arr = np.array([1,2,3,4,5])
#               0,1,2,3,4
#                     -2,-1
print(arr[3])
print(arr[-1])

4
5


In [16]:
# arr[row][col]
arr_2d = np.array([[1,2,3], [4,5,6], [7,8,9]])
print(arr_2d)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [18]:
print(arr_2d[0][1])
print(arr_2d[1][2])

2
6


In [19]:
# Slicing
"""
array[start:stop:step]
- start : Starting Index (default 0)
- stop: Ending Index (exclusive)
- step: Step size (default 1)
"""

'\narray[start:stop:step]\n- start : Starting Index (default 0)\n- stop: Ending Index (exclusive)\n- step: Step size (default 1)\n'

In [26]:
# 1D Array Slice
arr_1d = np.array([1,2,3,4,5,6])
#                  0,1,2,3,4,5

print(arr_1d[3:])
print(arr_1d[1:4])
print(arr_1d[::3])
print(arr_1d[:3])
print(arr_1d[0:5:2])

[4 5 6]
[2 3 4]
[1 4]
[1 2 3]
[1 3 5]


In [31]:
# 2D Array
arr_2d = np.array([[1,2,3], [4,5,6], [7,8,9]])
"""
   0 1 2
0 [1,2,3]
1 [4,5,6]
2 [7,8,9]
"""
# Slice Row and Column [0, 1] arr[row, col]
print(arr_2d[0:2, 1:3])
print(arr_2d[:, 1])
print(arr_2d[2, :])

[[2 3]
 [5 6]]
[2 5 8]
[7 8 9]


In [32]:
print(arr_2d[-2:, -2:])

[[5 6]
 [8 9]]


In [41]:
# Boolean Indexing
arr_bool = np.array([10,20,30,40,50])
print(arr_bool[arr_bool>25])
print(arr_bool[(arr_bool > 25) & (arr_bool < 45)])

[30 40 50]
[30 40]


In [42]:
# Fancy Indexing
arr_fancy = np.array([10,20,30,40,50])
indices = [0 ,2, 4]
print(arr_fancy[indices])

[10 30 50]


In [44]:
arr_fancy_2d = np.array([[1,2,3], [4,5,6], [7,8,9]])
rows = [1, 2, 0] # last two rows
cols =  [0, 1, 2]
print(arr_fancy_2d[rows, cols]) # arr_fancy_2d[1][0], arr_fancy_2d[2][1], arr_fancy_2d[0][2]

[4 8 3]


In [47]:
# Slice to reverse Array array[start:stop:end]
arr = np.array([10,20,30,40,50])
print(arr)
print(arr[::-1])

[10 20 30 40 50]
[50 40 30 20 10]


# Numpay looping using nditer function

In [50]:
arr = np.array([10,20,30,40,50])
for value in arr:
    print(value)
    value = 10
print(arr)

10
20
30
40
50
[10 20 30 40 50]


In [49]:
for value in np.nditer(arr):
    print(value)

10
20
30
40
50


In [54]:
arr_2d = np.array([ [1,2,3], [4,5,6] ])
print(arr_2d)
for value in np.nditer(arr_2d):
    print(value)
print("---------")
for arr_1d in arr_2d:
    for value in arr_1d:
        print(value)

[[1 2 3]
 [4 5 6]]
1
2
3
4
5
6
---------
1
2
3
4
5
6


In [58]:
arr_2d = np.array([[1,2,3],[4,5,6] ])
print(arr_2d)

# Enable the write mode
for element in np.nditer(arr_2d, op_flags=['readwrite']):
    element[...] = element * 2 # Multiplu each element by 2 # ... denote the current index

print()
print(arr_2d)

[[1 2 3]
 [4 5 6]]

[[ 2  4  6]
 [ 8 10 12]]


In [1]:
# How to diable safe check...
arr_float = np.array([1.5, 2.7, 3.5])
for value in np.nditer(arr_float, flags=['buffered'], op_dtypes=['int']):
    print(value)

NameError: name 'np' is not defined

# Copy , View in Numpy

In [2]:
# Copy (slow)
# Create a new clone it's going to use more memory

In [3]:
import numpy as np

In [6]:
arr_1d = np.array([1,2,3,4,5])

arr_copy = arr_1d.copy()

arr_1d[0] = 99

print(arr_1d)
print(arr_copy)

[99  2  3  4  5]
[1 2 3 4 5]


In [7]:
# View (fast)
# Create a view on the exisitng data

In [11]:
arr_1d = np.array([1,2,3,4,5])

arr_view = arr_1d.view()

arr_1d[0] = 99
arr_view[-1] = 100

print(arr_1d)
print(arr_view)

[ 99   2   3   4 100]
[ 99   2   3   4 100]


# Joining & Spilling Array

# axis
```
1-D
[7, 8, 9,10]
-----> axis 0

2-D
axis-0 (row)
| [1,2,3]
| [4,5,6]
| [7,8,9]
\/
------> axis-1 (col)
```

In [16]:
# Joining Array
# Syntex: np.concatenate((arr1, arr2, arr3,....), axis=0)
# [1,2,3] [4,5,6] => [1,2,3,4,5,6]

arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])

result = np.concatenate((arr1, arr2))
print(result)

[1 2 3 4 5 6]


In [18]:
arr1 = np.array([[1,2], [3,4]])
"""
[1,2]
[3,4]
"""
arr2 = np.array([[5,6]])
"""
[5,6]
"""
##########
"""
[1,2]
[3,4]
[5,6]
"""
result = np.concatenate((arr1, arr2), axis = 0)
print(result)

[[1 2]
 [3 4]
 [5 6]]


In [21]:
"""
[1,2] Join T([5, 6]) = [5]
[3,4]                  [6]
"""
result = np.concatenate((arr1, arr2.T), axis = 1)
print(result)

[[1 2 5]
 [3 4 6]]


In [24]:
# Stack
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])
arr3 = np.array([7,8,9])

result = np.stack((arr1, arr2)) # 2D Array
print(result)

[[1 2 3]
 [4 5 6]]


In [25]:
result = np.stack((arr1, arr2, arr3), axis=1) # 2D Array
print(result)

[[1 4 7]
 [2 5 8]
 [3 6 9]]


In [27]:
#Spilling Array

arr = np.array([1,2,3,4,5,6])
# Split into 3 parts
result = np.array_split(arr, 2)
print(result)

[array([1, 2, 3]), array([4, 5, 6])]


In [29]:
arr = np.array([[1,2],[3,4],[5,6],[7,8]])
"""
1,2
3,4
5,6
7,8
"""
# Split along row
result = np.array_split(arr, 2, axis=0)
print(result)

[array([[1, 2],
       [3, 4]]), array([[5, 6],
       [7, 8]])]


In [34]:
# Split along col
result = np.array_split(arr, 2, axis=1)
print(result)

[array([[1],
       [3],
       [5],
       [7]]), array([[2],
       [4],
       [6],
       [8]])]


# Numpy Array Function

In [35]:
# where()

# np.where(condition, [x,y])
# condtion: condition to filter data
# X, Y (optional) replace the value of X where conditon is true else replace with Y

In [37]:
arr = np.array([10,20,30,40,50])

#Return the indices of the array
indices = np.where(arr > 25)
print(indices)

(array([2, 3, 4]),)


In [39]:
# Replace the element > 25 with 99
result = np.where(arr > 25, 99, 0)
#[0,0,99,99,99]
print(result)

[ 0  0 99 99 99]


In [40]:
# searchsorted()
# it work on sorted array

# np.searchsorted(arr, value, side='left')

In [45]:
arr = np.array([10,20,30,40,50])
index = np.searchsorted(arr, 30)
print(index)

2


In [49]:
# Where you can insert 25 in the array so sorted order is also maintain
# [10,20,25,30,40,50]
#  0, 1, 2
index = np.searchsorted(arr, 20, side='right')
print(index)

index = np.searchsorted(arr, 35)
print(index)

2
3


In [50]:
#sort()
#Syntex: np.sort(array, axis=-1, kind='quicksort')  axis=-1 (denote the last axis)

In [51]:
arr = np.array([45, 12, 44, 7, 9, 66, 56])
sorted_arr = np.sort(arr)
print(sorted_arr)

[ 7  9 12 44 45 56 66]


In [62]:
arr_2d = np.array([[30, 44, 20], [50, 40, 60]])
"""
30,44,20
50,40,60
"""
sorted_arr_2d_col = np.sort(arr_2d, axis = 0) # Sort along row = 1, col = 0
print(sorted_arr_2d_col)
print()
sorted_arr_2d_row = np.sort(arr_2d, axis = 1, kind='mergesort') # Sort along row = 1, col = 0
print(sorted_arr_2d_row)

[[30 40 20]
 [50 44 60]]

[[20 30 44]
 [40 50 60]]


In [63]:
# Filter Array (Boolean Masking)

arr = np.array([10, 20, 30, 40, 50, 60])
#               [False, False, True,  True, True]
print(arr[arr > 25])

[30 40 50 60]


In [64]:
bool_array = [True, False, False, False, False, True]
print(arr[bool_array])

[10 60]


In [65]:
print(arr[(arr > 25) & (arr < 50)])

[30 40]


In [70]:
#Shuffling

arr = np.array([10, 20, 30, 40, 50, 60])
print(arr)
print()
np.random.shuffle(arr)
print(arr)

[10 20 30 40 50 60]

[50 10 60 40 30 20]


In [75]:
arr_2d = np.array([[30, 44, 20], [50, 40, 60]])
print(arr_2d)
print()
np.random.shuffle(arr_2d)
print(arr_2d)

[[30 44 20]
 [50 40 60]]

[[30 44 20]
 [50 40 60]]


In [77]:
# Unique values
arr = np.array([10, 10, 30, 30, 50, 60])
uniqe_element = np.unique(arr)
print(uniqe_element)

[10 30 50 60]
