# Numpy

# Numerical Python designed for numerical operation

- N - dimensionl Array
- Math Operation
- Broadcasting
- Integrate with other liberary (pandas, Matploib, TensorFLow)
- Effciency (Written in C language)
- Memory Efficiency

# pip install numpy

In [5]:
import numpy as np #(Shift + Enter)

In [6]:
arr = np.array([1,2,3,4])

In [9]:
print(arr)
print(type(arr))

[1 2 3 4]
<class 'numpy.ndarray'>


In [10]:
l = [1, 2, 3, 4]
print(l)
print(type(l))

[1, 2, 3, 4]
<class 'list'>


# Numpy Vs Python List

# Speed

In [11]:
import time

In [12]:
#NumPy Array
arr = np.arange(1000000) #[0 1 2 3 .... 1000000]
start = time.time()
arr = arr * 2
print("NumPy Time: ", time.time() -  start)

NumPy Time:  0.002199888229370117


In [14]:
#Python List
lst = list(range(1000000)) #[0 1 2 3 .... 1000000]
start = time.time()
lst = [x * 2 for x in lst]
print("Python List Time: ", time.time() -  start)

Python List Time:  0.03722500801086426


# Memory Efficiency

In [16]:
import sys

In [17]:
# NumPy Array
arr = np.array([1, 2, 3, 4])
print("Numpy Array Memory:", arr.nbytes, "bytes")

Numpy Array Memory: 32 bytes


In [18]:
# Python List
lst = [1, 2, 3, 4]
print("Python List Memory: ", sys.getsizeof(lst) + sum(sys.getsizeof(x) for x in lst), "bytes")

Python List Memory:  200 bytes


# Type Consistency

In [19]:
lst = [1, 2, 3, 4, "Mohit"]

In [20]:
lst

[1, 2, 3, 4, 'Mohit']

In [23]:
arr = np.array([1, 2, 3, 4, "Mohit"])

In [24]:
arr

array(['1', '2', '3', '4', 'Mohit'], dtype='<U21')

# Math Operation

In [36]:
#Numpy Array ()
arr = np.array([1, 2, 3, 4])
print("NumPy Sum:", np.sum(arr))
print("NumPy Mean:", np.mean(arr))

NumPy Sum: 10
NumPy Mean: 2.5


In [37]:
%timeit np.sum(arr)

939 ns ± 14.5 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)


In [33]:
lst = [1, 2, 3, 4]
print("Python Sum:", sum(lst))
print("Python Mean:", sum(lst)/len(lst))

Python Sum: 10
Python Mean: 2.5


In [38]:
%timeit sum(lst)

30.6 ns ± 1.43 ns per loop (mean ± std. dev. of 7 runs, 10,000,000 loops each)


# ARRAY

In [40]:
x = [1, 2, 3 ,4]
y = np.array(x)
print(y)
print(type(y))
y = np.array([1, 2, 3, 4, 5])
print(y)
print(type(y))

[1 2 3 4]
<class 'numpy.ndarray'>
[1 2 3 4 5]
<class 'numpy.ndarray'>


In [41]:
l = []
for i in range(1,5):
    val = int(input("enter:"))
    l.append(val)

print(np.array(l))

enter: 10
enter: 11
enter: 12
enter: 13


[10 11 12 13]


# Dimension in Array
- 1-D Array
- 2-D Array
- 3-D Array
- Higher Dimensional Array

In [43]:
x = [1, 2 ,3 ,4]
y = np.array(x)
print(y.ndim)

1


In [45]:
ar2 = np.array([[1, 2, 3], [4, 5, 6]])
print(ar2)
print(ar2.ndim)

[[1 2 3]
 [4 5 6]]
2


In [47]:
ar3 = np.array([[[1, 2, 3], [1, 2, 3], [1, 2, 3]]])
print(ar3)
print(ar3.ndim)

[[[1 2 3]
  [1 2 3]
  [1 2 3]]]
3


In [49]:
arn = np.array([1, 2, 3, 4], ndmin = 10)
print(arn)
print(arn.ndim)

[[[[[[[[[[1 2 3 4]]]]]]]]]]
10


# Special NumPy Array

- Array Fill with 0's
- Array Fill with 1's
- Create an empty array (junk)
- Range array
- Array diagonal element filled with 1's
- Create an array with values that are spaced lineraly in specified interval

In [57]:
zeros_array = np.zeros((5, 10)) # 5 - Row, 10 - Col
print(zeros_array)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


In [56]:
ones_array = np.ones((4, 5))
print(ones_array)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [67]:
empty = np.empty((4, 4))
print(empty)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [73]:
range_array = np.arange(0, 10, 1) # Start = 0 Stop = 10 Step = 2
print(range_array)

[0 1 2 3 4 5 6 7 8 9]
